---
- name: Aplicar manifests Kubernetes no GKE
  hosts: localhost
  connection: local

  vars:
    manifests_path: ./kubernetes-deployments
    kubeconfig_path: "{{ lookup(\'env\', \'K8S_AUTH_KUBECONFIG\') }}"

  tasks:
    - name: Clonar repositório com os manifests
      git:
        repo: https://github.com/WEBcko/kubernetes-deployments.git
        dest: "{{ manifests_path }}"
        force: yes

    - name: Buscar todos os arquivos YAML recursivamente
      find:
        paths: "{{ manifests_path }}"
        recurse: yes
        patterns: "*.yaml"
      register: yaml_files

    - name: Aplicar todos os manifests no cluster GKE
      loop: "{{ yaml_files.files }}"
      k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        src: "{{ item.path }}"
        
